Fixes an error with outros and elseifs
This is a fix for when an elseif doesn't have a final else, and the following error was thrown:

```
TypeError: Cannot read property 'o' of undefined
```

See https://svelte.technology/repl?version=2.12.0&gist=c33d308077447f8ba06b79d8ef5ab1e4